import type { CandidateAnalysis, AnalysisLog } from '../types';
import type { Deal } from '../types/pipeline';
import { isV3Enabled } from '../lib/persistence/keys';
import { usePipelineStore } from '../store/pipelineStore';

/**
 * Export a single analysis as formatted text for clipboard/sharing
 */
export function analysisToText(a: CandidateAnalysis): string {
  const lines: string[] = [
    `CANDIDATE ANALYSIS — ${a.candidateName}`,
    `Role: ${a.jobTitle}`,
    `Date: ${new Date(a.timestamp).toLocaleDateString()}`,
    `Match: ${a.matchScore}% | Verdict: ${a.verdict}`,
    '',
    'PROFILE',
    a.profileSummary,
    '',
    'PILLAR SCORES',
    ...a.pillarScores.map(
      (p) => `  ${p.pillarName}: ${p.score}/10 [${p.riskLevel}] — ${p.evidence}`
    ),
    '',
    'GREEN FLAGS',
    ...a.greenFlags.map((f) => `  + ${f}`),
    '',
    'RED FLAGS',
    ...a.redFlags.map((f) => `  - ${f}`),
  ];

  if (a.autoRedFlags.length > 0) {
    lines.push('', 'AUTO-DETECTED FLAGS');
    a.autoRedFlags.forEach((f) =>
      lines.push(`  [${f.severity.toUpperCase()}] ${f.type}: ${f.description}`)
    );
  }

  lines.push(
    '',
    'INTERVIEW QUESTIONS',
    ...a.truthTestQuestions.map(
      (q, i) => `  ${i + 1}. ${q.question}\n     (Verifies: ${q.intent})`
    ),
    '',
    'RECRUITER NOTES',
    `  Outreach: ${a.recruiterNotes.outreachAngle}`,
    `  Salary Est: ${a.recruiterNotes.salaryEstimate}`,
    `  Notes: ${a.recruiterNotes.additionalNotes}`,
    '',
    '---',
    'Generated by Revital | CV Analyzer',
  );

  return lines.join('\n');
}

/**
 * Pipeline stage for a legacy analysis id (AnalysisLog.id === analysis.id;
 * Deal.analysisId links back). Empty string when no v3 deal exists or the
 * v3 flag is off — never a guess. Tombstoned deals are ignored; if several
 * live deals reference the analysis, the most recently updated wins.
 */
export function dealStageForAnalysis(
  analysisId: string,
  deals?: Deal[]
): string {
  const source =
    deals ?? (isV3Enabled() ? usePipelineStore.getState().deals : []);
  const live = source.filter((d) => !d.deleted && d.analysisId === analysisId);
  if (live.length === 0) return '';
  const latest = live.reduce((a, b) => (b.updatedAt > a.updatedAt ? b : a));
  return latest.stage;
}

/**
 * Export log as CSV.
 * Wave 2 (lead-granted): a `Stage` column is APPENDED LAST — the legacy
 * columns (Date..Summary) stay byte-identical to the Wave-1 output.
 * `deals` is injectable for tests/callers; by default the v3 pipeline
 * store is consulted only while the v3 flag is on (read-only).
 */
export function logToCSV(log: AnalysisLog[], deals?: Deal[]): string {
  const header = 'Date,Candidate,Job Title,Score,Verdict,Summary,Stage';
  const rows = log.map(
    (e) =>
      `"${new Date(e.timestamp).toLocaleDateString()}","${e.candidateName}","${e.jobTitle}",${e.matchScore},"${e.verdict}","${e.summary}"` +
      `,"${dealStageForAnalysis(e.id, deals)}"`
  );
  return [header, ...rows].join('\n');
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}

/**
 * Download text as file
 */
export function downloadFile(content: string, filename: string, type = 'text/plain') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
