import type { CandidateAnalysis, AnalysisLog } from '../types';

/**
 * Export a single analysis as formatted text for clipboard/sharing
 */
export function analysisToText(a: CandidateAnalysis): string {
  const lines: string[] = [
    `CANDIDATE ANALYSIS — ${a.candidateName}`,
    `Role: ${a.jobTitle}`,
    `Date: ${new Date(a.timestamp).toLocaleDateString()}`,
    `Match: ${a.matchScore}% | Verdict: ${a.verdict}`,
    '',
    'PROFILE',
    a.profileSummary,
    '',
    'PILLAR SCORES',
    ...a.pillarScores.map(
      (p) => `  ${p.pillarName}: ${p.score}/10 [${p.riskLevel}] — ${p.evidence}`
    ),
    '',
    'GREEN FLAGS',
    ...a.greenFlags.map((f) => `  + ${f}`),
    '',
    'RED FLAGS',
    ...a.redFlags.map((f) => `  - ${f}`),
  ];

  if (a.autoRedFlags.length > 0) {
    lines.push('', 'AUTO-DETECTED FLAGS');
    a.autoRedFlags.forEach((f) =>
      lines.push(`  [${f.severity.toUpperCase()}] ${f.type}: ${f.description}`)
    );
  }

  lines.push(
    '',
    'INTERVIEW QUESTIONS',
    ...a.truthTestQuestions.map(
      (q, i) => `  ${i + 1}. ${q.question}\n     (Verifies: ${q.intent})`
    ),
    '',
    'RECRUITER NOTES',
    `  Outreach: ${a.recruiterNotes.outreachAngle}`,
    `  Salary Est: ${a.recruiterNotes.salaryEstimate}`,
    `  Notes: ${a.recruiterNotes.additionalNotes}`,
    '',
    '---',
    'Generated by Revital | CV Analyzer',
  );

  return lines.join('\n');
}

/**
 * Export log as CSV
 */
export function logToCSV(log: AnalysisLog[]): string {
  const header = 'Date,Candidate,Job Title,Score,Verdict,Summary';
  const rows = log.map(
    (e) =>
      `"${new Date(e.timestamp).toLocaleDateString()}","${e.candidateName}","${e.jobTitle}",${e.matchScore},"${e.verdict}","${e.summary}"`
  );
  return [header, ...rows].join('\n');
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text);
}

/**
 * Download text as file
 */
export function downloadFile(content: string, filename: string, type = 'text/plain') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
